docs: Added room documentation
godot-escoria/escoria-docs pull request #40
Opened 2022-01-14 20:47 UTC by dploeger

2022-01-18 06:34 UTC, StraToN approved these changes

2022-01-19 18:43 UTC, BHSDuncan requested changes
Please address the single comment left in the PR. Other than that, I've made some edits, and the rest looks good!

2022-01-19 18:43 UTC, BHSDuncan commented on getting_started/backgrounds.rst
> +react to different light sources in the show picture.
Can you maybe re-word the ending of this paragraph? It isn't really clear what you mean by "light sources in the show picture".

2022-01-20 18:50 UTC, dploeger commented
Fixed, and I also included a fix in the step by step guide that came up on the Discord in the last days.

2022-01-20 18:59 UTC, BHSDuncan approved these changes
Made a small changing to phrasing but otherwise everything else looks good!

2022-01-20 19:00 UTC, merged