feat: Updated angle diagrams
godot-escoria/escoria-docs pull request #49
Opened 2022-04-11 07:57 UTC by balloonpopper

Based on the feedback in the help channel the other day I've updated the documentation about character angles.

2022-04-16 00:57 UTC, BHSDuncan requested changes

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +   :alt: A visual representation character motion matching set animations to
```suggestion
   :alt: A visual representation of character motion matching set animations to
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +degrees.) When the player moves the character in a direction that isn't one of
```suggestion
degrees). When the player moves the character in a direction that isn't one of
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +these angles however, Escoria needs to work out which animation the developer
```suggestion
these angles, however, Escoria needs to work out which animation the developer
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +correspond to the up animation.
```suggestion
correspond to the "up" animation.
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +direction character table below.
```suggestion
Click on each resource and set its angle start and size settings based on the
8-direction character table below.
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +8 Direction Character
```suggestion
8-direction Character
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +2 Direction Character
```suggestion
2-direction Character
```

2022-04-16 00:57 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +4 Direction Character
```suggestion
4-direction Character
```

2022-04-16 18:09 UTC, BHSDuncan approved these changes

2022-04-21 08:40 UTC, StraToN approved these changes

2022-04-21 08:41 UTC, merged