feature: Added changing costume documentation
godot-escoria/escoria-docs pull request #50
Opened 2022-04-17 14:25 UTC by balloonpopper

Added documentation for changing character costume. Renamed the "other" documentation to FAQ and changed the headings to match.
Fixes : https://github.com/godot-escoria/escoria-issues/issues/185

2022-04-18 01:18 UTC, BHSDuncan requested changes

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +an entirely new character (i.e. a new Godot Scene with an ESCPlayer node,
```suggestion
an entirely new character (i.e. a new Godot Scene with an `ESCPlayer` node,
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +animated sprite, collision area, etc). The second option is to change just the
```suggestion
animated sprite, collision area, etc). The second option is to change the
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +This option might be appropriate if you needed to change something fundamental
```suggestion
This option might be appropriate if you need to change something fundamental
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +then in your game room (ESCRoom) set the PlayerScene parameter to point at the
```suggestion
then in your game room (`ESCRoom`) set the `Player Scene` parameter to point at the
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +Changing the character animations
```suggestion
Changing the character animations
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +glasses, or changing their clothes for example) is an easy task. The process
```suggestion
glasses, or changing their clothes, for example) is an easy task. The process
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +to use the animations as the default at the appropriate time.
```suggestion
to use the animations as its default at the appropriate time.
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +You should already have idle, talk and walk animations defined for your
```suggestion
You should already have idle, talk, and walk animations defined for your
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +jester clothes.
```suggestion
appropriate. In this example, the demonstration character has had some
jester clothes put on.
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +Go back to your character (ESCPlayer) node and using the dropdown arrow on the
```suggestion
Go back to your character (`ESCPlayer`) node and, using the dropdown arrow on the
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +Use the dropdown again choosing the **save** option. Give the file
```suggestion
Use the dropdown again, choosing the **save** option. Give the file
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +an appropriate name and location in the file dialogue window that appears.
```suggestion
an appropriate name and location in the file dialog window that appears.
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +want to use them. If the player buys a Jester outfit for example, you may
```suggestion
want to use them. If the player buys a Jester outfit, for example, you may
```

2022-04-18 01:18 UTC, BHSDuncan commented on advanced/faq.rst
> +Remaps).
```suggestion
providing language support. Translation information is found in Godot's
`Project/Project Settings/Localization` menu (text in `Translations`, audio in
`Remaps`).
```

2022-04-19 04:29 UTC, balloonpopper commented on advanced/faq.rst
> +Changing the character animations
@BHSDuncan  I'll add this separately. Git won't let me accept this suggestion for unknown reasons.

2022-04-19 11:21 UTC, StraToN approved these changes

2022-04-19 13:31 UTC, StraToN commented
Fixes https://github.com/godot-escoria/escoria-issues/issues/27

2022-04-19 16:15 UTC, BHSDuncan approved these changes

2022-04-21 08:39 UTC, merged