Adds in a description and example of using the ESC command called 'cu…
godot-escoria/escoria-docs pull request #54
Opened 2022-05-02 21:09 UTC by BHSDuncan

…stom'.

2022-05-03 12:28 UTC, balloonpopper requested changes
I updated the language a little to make it consistent with the rest of the FAQ (the format of the question, and "ESC" to "Escoria script" for example). I also added a concrete example so users have something to copy.

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +--------------------------------------------------------------------
```suggestion
How can I call my own GDScript function from Escoria?
-----------------------------------------------------
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +must be associated with the child node of an `ESCItem` in your scene.
```suggestion
Escoria script makes this possible by providing the `custom` command. The function
must be associated with the child node of an `ESCItem` in your scene.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +  door.
```suggestion
* Create a new node of an appropriate type as a child of an `ESCItem` in your
  scene. For example, if you have a door in your scene and you want to make a
  function that does something special when the door opens, you could create a
  child node of type `Node2D` underneath the `ESCItem` that represents the
  door.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +   `custom` command.
```suggestion
.. hint::

   Remember the global ID and name of this `ESCItem`. 
   You'll need them when you use the `custom` command.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +  doesn't require any arguments, Escoria will pass in an empty array.
```suggestion
* Create your GDScript function in a .gd file and attach it to the child node
  as described above. This function can be called anything you want, but it
  **must** take exactly one argument. Escoria will pass in to the function any and
  all arguments specified in the `custom` command as an array. If your function
  doesn't require any arguments, Escoria will pass in an empty array.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +
```suggestion
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +  well as to perform any validation on these arguments you deem necessary.
```suggestion
  It is up to you to unpack the arguments passed in via the `custom` command as
  well as performing any validation on these arguments you deem necessary.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +
```suggestion
* In the appropriate event in an Escoria script file, call the function you made
  above by using the `custom` command. For example :
     * Your game has a node with a global_id of "treasure_maps"
     * The "treasure_maps" node a child node called "france_treasure_map".
     * "france_treasure_map" has a Godot script (in GDscript format) attached. 
        In this script is a function "draw_treasure" to show a map on the screen.
       In your Escoria script, you would call the script using :

.. code-block::

   :setup
   # Call the function you defined with some arguments
   # Format : custom esc_item_global_id child_node_name function_name arg1 arg2 ... 
   # Note no parameters are passed to the "draw_treasure" function
   custom treasure_maps france_treasure_map draw_treasure 
   
     * The GDScript it calls might look like this :

.. code-block::

   extends Node2D

   # An empty array is passed as a parameter to the function so we ignore it
   func draw_treasure(_ignored_parameter):
	get_node("../france_map_sprite").visible = true

* If instead you wanted to pass this script some parameters:
   * If your script took an x and y coordinate to display an "X marks the spot"
      graphic on the treasure map, your Escoria script code might look like :

.. code-block::

   :setup
   custom treasure_maps france_treasure_map draw_treasure xcoordinate ycoordinate

   * The matching GDScript code now needs to extract those coordinates from the 
      parameter array that is passed to the function.

.. code-block::

   extends Node2D

   # Extract coordinates from the array of parameters
   func draw_treasure(list_of_parameters):
	var xcoord = list_of_parameters[0]
	var ycoord = list_of_parameters[1]
	get_node("../france_map_sprite").visible = true
	[...]

```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +   Variables like ESC flags, globals and the like cannot be used currently.
```suggestion
.. hint::

   Any arguments you pass to your function must be literals.
   Escoria variables (ESC flags, globals, etc) cannot be passed currently.
```

2022-05-03 12:28 UTC, balloonpopper commented on advanced/faq.rst
> +That's all there is to it!
```suggestion
```

2022-05-03 15:06 UTC, BHSDuncan commented on advanced/faq.rst
> +  door.
Frankly, in this context, they're interchangeable, but for the sake of consistency (given that you've done more work on the docs now than I have), I'll use your suggestion.

2022-05-03 15:12 UTC, BHSDuncan commented on advanced/faq.rst
> +  well as to perform any validation on these arguments you deem necessary.
Disagree here. While your suggestion does sound good, consistency between the two instructions and the preceding subject has to be maintained. 

I.e. if the first item wasn't there (about unpacking), we'd say, "It is up to you to perform any validation...", not "It is up to you performing validation...".

However, if you feel strongly enough... :)

2022-05-04 08:44 UTC, balloonpopper commented on advanced/faq.rst
> +   * The matching GDScript code now needs to extract those coordinates from the
```suggestion

.. hint::

   Escoria variables (ESC flags, globals, etc) can be passed as 
   parameters by wrapping them in braces.
   e.g. {xcoorinate}

   * The matching GDScript code now needs to extract those coordinates from the 
```

2022-05-04 08:44 UTC, balloonpopper commented on advanced/faq.rst
> +   custom treasure_maps france_treasure_map draw_treasure xcoordinate ycoordinate
```suggestion
   custom treasure_maps france_treasure_map draw_treasure {xcoordinate} {ycoordinate}
```

2022-05-04 08:45 UTC, balloonpopper commented
Added 2 changes based on https://github.com/godot-escoria/escoria-demo-game/pull/593

2022-05-04 10:27 UTC, balloonpopper approved these changes

2022-05-15 16:22 UTC, StraToN approved these changes
No problem with the text. Just the doc8 fixes to be done. Thanks!

2022-05-16 09:23 UTC, merged

2022-05-16 09:23 UTC, StraToN commented
Thanks a lot!