feature: Some clarification on the walking animation names
godot-escoria/escoria-docs pull request #55
Opened 2022-05-05 09:42 UTC by balloonpopper

2022-05-05 20:00 UTC, BHSDuncan requested changes

2022-05-05 20:00 UTC, BHSDuncan commented on getting_started/step_by_step/2_create_player_character.rst
> +   one AnimatedSprite node for the character.
```suggestion
   one `AnimatedSprite` node for the character.
```

2022-05-06 21:22 UTC, BHSDuncan approved these changes

2022-05-15 16:23 UTC, StraToN approved these changes

2022-05-15 16:23 UTC, merged