Update 5_adding_items.rst
godot-escoria/escoria-docs pull request #59
Opened 2022-07-04 14:33 UTC by jeangit

putting the dialog above the Graham's head, and not at the top of the screen (by default)

2022-07-04 15:55 UTC, BHSDuncan requested changes

2022-07-04 15:55 UTC, BHSDuncan commented on getting_started/step_by_step/5_adding_items.rst
> +
```suggestion
If you don't define an ``ESCLocation`` in your player scene, dialog will
appear at the top of the screen.

So add an ``ESCLocation`` as a child of ``ESCPlayer``.

Name this node "dialog_position" (this name is mandatory).

By default, dialog will appear under the character. You can move the node above
Graham's head to have dialog appear in a more regular location.

```

2022-07-04 17:01 UTC, BHSDuncan approved these changes

2022-07-05 06:07 UTC, StraToN approved these changes

2022-07-05 06:07 UTC, StraToN commented
Thanks a lot !

2022-07-05 06:07 UTC, merged