fix: Correct documentation about event flags
godot-escoria/escoria-docs pull request #63
Opened 2022-11-27 02:37 UTC by balloonpopper

2022-11-28 07:01 UTC, StraToN approved these changes

2022-11-29 03:13 UTC, BHSDuncan requested changes

2022-11-29 03:13 UTC, BHSDuncan commented on esc_reference.template.rst
> +(the ESC location "door1" or "door2") depending on the last visited scene.
```suggestion
(the `ESCLocation` "door1" or "door2") depending on the last visited scene.
```

2022-11-29 03:13 UTC, BHSDuncan commented on esc_reference.template.rst
> +For example :
```suggestion
For example:
```

2022-11-29 03:44 UTC, BHSDuncan approved these changes

2022-11-29 09:29 UTC, merged